# Generated by Django 5.0.2 on 2024-02-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productgallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, upload_to='photo/categories')),
                ('photo2', models.ImageField(blank=True, upload_to='photo/categories')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('sub_name', models.CharField(blank=True, max_length=255)),
                ('description1', models.TextField()),
                ('description_block1_2', models.TextField()),
                ('description_block2_2', models.TextField()),
                ('description_block3', models.TextField()),
                ('description_block1_4', models.TextField()),
                ('description_block2_4', models.TextField()),
            ],
        ),
    ]
