# Generated by Django 5.0.2 on 2024-02-22 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description_block1_2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description_block1_4',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description_block2_2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='description_block3',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='sub_name',
        ),
    ]
