# Generated by Django 5.0.2 on 2024-02-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_shop_description1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_bar',
            field=models.IntegerField(default=True),
        ),
    ]
