# Generated by Django 5.0.2 on 2024-02-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userprofile_address_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo1', models.ImageField(blank=True, default=False, upload_to='userprofile')),
                ('photo2', models.ImageField(blank=True, default=False, upload_to='userprofile')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('sub_name', models.CharField(blank=True, max_length=255)),
                ('description1', models.TextField(max_length=255)),
                ('description_block1_2', models.TextField(max_length=255)),
                ('description_block2_2', models.TextField(max_length=255)),
                ('description_block3', models.TextField(max_length=255)),
                ('description_block1_4', models.TextField(max_length=255)),
                ('description_block2_4', models.TextField(max_length=255)),
            ],
        ),
    ]
