# Generated by Django 5.0.2 on 2024-02-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='photo1',
            field=models.ImageField(blank=True, upload_to='photo/categories'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='photo2',
            field=models.ImageField(blank=True, upload_to='photo/categories'),
        ),
    ]
