# Generated by Django 5.0.2 on 2024-02-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='size',
        ),
    ]
